---
- hosts: raspis
  remote_user: ubuntu
  
  tasks:
    
    - name: install java jre & jdk
      become: yes
      apt:
        pkg:
        - default-jre
        - default-jdk
        update_cache: yes
        state: latest
  
