---
- hosts: raspis
  remote_user: ubuntu
  become: yes
  
  tasks:
  
  - name: create project directory
    file:
      path: /home/ubuntu/projects/picluster/spark/
      state: directory
  
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
  
  - name: install tree
    apt: 
      pkg: tree
